# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gjZUu084IltBuBfjYVu4ctBtO_VM1qOm
"""

from setuptools import setup, find_packages

setup(
    name='Personalised Medication Recommendation Dashboard',
    version='1.0.0',
    author='Aslesha Sanjana Kodavali','Asmitha Ramesh'
    description='A Streamlit dashboard for personalized medication recommendation with SHAP interpretability.',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'streamlit>=1.32',
        'pandas>=1.5',
        'numpy>=1.21',
        'scikit-learn>=1.3',
        'matplotlib>=3.5',
        'plotly>=5.15',
        'shap>=0.44',
        'joblib>=1.2',
        'xgboost>=1.7',
    ],
    entry_points={
        'console_scripts': [
            'run_dashboard = dashboard.app:main'
        ],
    },
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
    ],
    python_requires='>=3.7',
)